

<html>
<head><title>Ajouter Categorie</title>
    <link rel="stylesheet" type="text/css" href="bootstrap/css/util.css">
    <link rel="stylesheet" type="text/css" href="bootstrap/css/main.css">
    <link rel="stylesheet" type="text/css" href="bootstrap/bootstrap.min.css">
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  
</head>
<body>
    
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="height: 60px;">
        <div class="container">
            
            <button 
                class="navbar-toggler" 
                type="button" 
                data-toggle="collapse" 
                data-target="#navbarResponsive" 
                aria-controls="navbarResponsive" 
                aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active le">
                <a class="nav-link" href="menu.php">Acceuil
                        
                    </a>
                </li>
                <li class="nav-item le">
                <a class="nav-link" href="listeProduit.php">Liste de produits</a>
                </li>
                <li class="nav-item le">
                <a class="nav-link" href="listeCategories.php">Liste de categories</a>
                </li>
                <?php if($logged):?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="deconnexion.php">Deconnexion</a>
                </li>
                <?php else:?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="login.php">Connexion</a>
                </li>
                <?php endif;?>
            </ul>
            </div>
        </div>
   </nav> 
        
        <div class="container-contact100 bg">
            <div class="wrap-contact100">
                <form class="contact100-form validate-form" method='POST'>
                    <span class="contact100-form-title">
                       <strong> Ajouter une categorie</strong>
                    </span>
                    
                    <div class="wrap-input100 validate-input">
                        <span class="label-input100">Nom du categorie</span>
                        <input class="input100" type="text" name="nom" value="">
                        <span class="focus-input100"></span>
                    </div>
                    
                    

                    
                    
                    <div class="wrap-input100 validate-input">
                        <span class="label-input100">Description</span>
                        <input class="input100" type="text" name="description" value=""></input>
                        <span class="focus-input100"></span>
                    </div>
                    

                    <!-- button editer -->
                    <div class="container-contact100-form-btn">
                        <div class="wrap-contact100-form-btn">
                            <div class="contact100-form-bgbtn .bg"></div>
                            <button class="contact100-form-btn" type="submit" value="envoyer" name="envoyer">
                                <span>
                                    Ajouter une categorie
                                    <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
		</div>
	</div>
    

</body>
</html>


<style>
    a {
        font-size: medium;
        font-family: 'Arial';
    }
    .le {
        position: relative;
        right: 300%;
    }
    body {
        position: absolute;
        width: 100%;
    }
    .toRight{
        position: absolute;
        left: 90%;
    }
   
    .bg {
        margin: 0;
        background: linear-gradient(45deg, #49a09d, #5f2c82);
        font-family: sans-serif;
        font-weight: 100;
    }
</style>

